---
course:
  term: "Fall 2024"
  office-hours: "TBD"
  teaching-assistants: "TBD"
  mid-term: "Oct 10"
  lectures:
    - "10:05am–11:25am Tuesday, Thursday (ENGMC 11)"
  tutorials:
    - "8:35am–10:25am Friday, (ENGMC 11)"
  labs:
    - "1:35pm-3:25pm Monday (TR 4090)"
    - "3:35pm–5:25pm Monday (TR 4090)"
    - "1:35pm–3:25pm Tuesday (TR 4090)"
    - "1:35pm–3:25pm Wednesday (TR 4090)"
    - "1:35pm–3:25pm Friday (TR 4090)"
---

# Course Outline {.unnumbered}

## General Information ({{< meta course.term >}})

Instructor
: -  Aditya Mahajan 
- *Office Hours*: {{< meta course.office-hours >}}

Teaching Assistants
: - {{< meta course.teaching-assistants >}} 

Lectures
: - {{< meta course.lectures >}} 

Tutorials
: - {{< meta course.tutorials >}} 

Everyone **must** be registered for the tutorial. Tutorials start from the **second** week of classes.

Labs
: - {{< meta course.labs.1 >}} 
: - {{< meta course.labs.2 >}} 
: - {{< meta course.labs.3 >}} 
: - {{< meta course.labs.4 >}} 
: - {{< meta course.labs.5 >}} 

Everyone **must** be registered for one lab. Labs start from the **second** week of classes.

The labs have to be done in groups of two. The groups will be formed in the first week of classs.  

Prerequisites
: - ECSE 206 (Fundamentals of Signals and Systems)
- ECSE 210 (Electrical Circuits 2)


Communication
: [Use the discussion board on myCourses]{.text-info} for all questions related to the course. Only personal emails related to medical exceptions for missing a deliverable will be answered.

## Graduate Attributes and Learning Outcomes

| Attribute | Description | Status |
|-----------|-------------|--------|
| KB | Knowledge Base for Engineering | Developed |
| PA | Problem Analysis | Developed |
| IN | Investigation | Developed |
| DE | Design | Introduced |

Upon the successful completion of this course, the student students will have demonstrated the ability to:

- Apply time- and frequency-domain tools to analyze linear time-invariant systems (KB, PA)
- Design controllers based on state-space methods and lead-lag compensators to meet time-response specifications (KB, PA, DE)
- Use Matlab to analyze and synthesize controllers for linear time-invariant systems (DE, IN)

## Course Content

| Week | Material Covered | 
|------|:-----------------|
| 1    | [Review of LTI Systems and Laplace Transforms](freq-modeling.qmd) |
| 2    | Pole Zero Plot Step response of first and second order systems, dominant pole approximation |
| 3    | State-space modeling, canoncial forms, transfer function of state space models |
| 4    | Matrix exponential and solution of matrix differential equations, time response of state space models | 
| 5    | Pole placement, controllability, and state feedback |
| 6    | Luenberger observer, observability, output feedback, and separation principle |
| 7    | Review and Mid-Term | 
| 8    | Routh-Hurwitz stability criterion. Special cases: zero in first column, row of zeros. |
| 9    | Block diagrams, rules for simplifying block diagrams, block diagram implementations of canonical forms of state space models | 
| 10   | System type, steady state error, disturbance rejection and sensitivity |
| 11   | Bode and Nyquist Plots |
| 12   | Nyquist stability criterion, gain and phase margins |
| 13   | Lead-Lag compensators

: {tbl-colwidths="[10,90]" .striped}

## Lab Schedule 

| Week | Lab | 
|------|:-----------------|
| 1    | No Labs | 
| 2    | Lab 1 : Introduction to Matlab |
| 3    | Lab 2 : Transfer functions and step response | 
| 4    | Lab 3 : System identification via Step Response | 
| 5    | Lab 4 : Eigenvalues and eigenvectors
| 6    | Lab 5 : State-Feedback Control (in simulation) | 
| 7    | Lab 6 : State-Feedback Control (in hardware) | 
| 8    | Lab 7 : Luenberger Observer for State Estimation | 
| 9    | Lab 8 : Output-Feedback Control | 
| 10   | Lab 9 : Block Diagram Reduction using Matlab |
| 11   | Lab 10 : System identification via Bode Plots | 
| 12   | Lab 11 : Nyquist stability criterion |
| 13   | Lab 12 : Lead-Lag compensator design |

: {tbl-colwidths="[10,90]" .striped}



## Course Material

Textbook
: - N. Nise, _Control Systems Engineering,_  7th Ed., Wiley

      Both paper and electronic versions of the textbook are available from the McGill bookstore. The electronic version of the book is also available from the publisher’s website and Google books.

  - R.L. Williams II and D.A. Lawrence, Linear State‐Space Control Systems, Wiley.

      The [electronic version of the book][LSSC] is available the library.

[LSSC]: https://onlinelibrary.wiley.com/doi/book/10.1002/9780470117873

Reference Books
: - G.F. Franklin, J. Powell, A. Emani-Naeini, _Feedback Control of Dynamical Systems_, 7th Ed., Pearson.
- K. Oagata, _Modern Control Engineering_, 5th Ed., Pearson.

## Evaluation

- **Assignments (20%)** Weekly homework assignments. Typically, each assignment will consist of four questions, out of which one or two randomly selected questions will be grader. The lowest two homework assignments will be dropped.

- **Laboratory (20%)** In-person weekly labs, to be conducted in groups of two. At the end of each lab, each group has to submit a lab report by filling in a Matlab Livescript template provided as part of the lab assignment.

- **Mid Term (20%)** Closed book in-class exam.
  [**{{< meta course.mid-term >}}**]{.text-danger} (during class time)

- **Final Exam (40%)** Closed book, in-person exam. Will be scheduled by the exam office and the dates will be announced later.

    The final exam will cover **all** the material seen in the class during the term.

## Marking policy

- Assignments must be submitted electronically on myCourses as a PDF. You may write the assignments on paper and then scan them as a PDF (there are several such apps available for all phone platforms), or write on a tablet and convert to PDF, or type using a word processor.

- **There will no make-up examination** for students who miss a mid-term.

  - Student who miss the exam due to a valid reason (see [Faculty of Engineering policy][policy]) should **notify the instructor within a week** of the exam and provide **necessary documentation**.

  - If, and only if, proper documentation for a missed exam is presented, the marks for the missed exam will be shifted to the final exam.

  - Students who miss the mid-term exam for any other reason (e.g., no medical note, going to the exam at the wrong time, or on the wrong day, etc.) will get zero marks on the exam.

- Any request for reevaluation of a mid-term or an assignment must be made **in writing within a week of its return**. Note that requesting a re-grade will mean that you **WHOLE** assignment or exam will be re-graded.

- [Due to paucity of grading hours, only one or two randomly selected questions will be graded in each assignment.]{.text-danger}

- The lowest two assignments and labs will be dropped. There will be no make-up for missed assignments and labs, _even if it is for a valid reason._ The whole point of dropping the lowest two assignments/labs is to reduce the administrative overhead of keeping track of such missed assignments/labs.


Right to submit in English or French written work that is to be graded.
: In accord with McGill University’s [Charter of Students’ Rights][charter], students in this course have the right to submit in English or in French any written work that is to be graded.

Academic Integrity
: McGill University values academic integrity. Therefore all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the [Code of Student Conduct and Disciplinary Procedures][code] (see McGill’s [guide to academic honesty][guide] for more information).

    L’université McGill attache une haute importance à l’honnêteté académique. Il incombe par conséquent à tous les étudiants de comprendre ce que l’on entend par tricherie, plagiat et autres infractions académiques, ainsi que les conséquences que peuvent avoir de telles actions, selon le [Code de conduite de l’étudiant et des procédures disciplinaires][code] (pour de plus amples renseignements, veuillez consulter le [guide pour l’honnêteté académique][guide] de McGill.)

## Course delivery

The course is taught in a “chalk and board” style; there will be no power point presentations. All students are expected to attend lectures and take notes. Partial notes on some of the material will be provided, but are not a substitute for the material covered in class.

© Instructor-generated course materials (e.g., handouts, notes, summaries, exam questions) are protected by law and may not be copied or distributed in any form or in any medium without explicit permission of the instructor. Note that infringements of copyright can be subject to follow up by the University under the Code of Student Conduct and Disciplinary Procedures.

## Additional Notes

- As the instructor of this course I endeavor to provide an inclusive learning environment. However, if you experience barriers to learning in this course, do not hesitate to discuss them with me or contact the office of [Student Accessibility and Achievement][OSD].

- [End-of-course evaluations][evaluations] are one of the ways that McGill works towards maintaining and improving the quality of courses and the student’s learning experience. You will be notified by e-mail when the evaluations are available. Please note that a minimum number of responses must be received for results to be available to students.


[policy]: https://www.mcgill.ca/engineering/students/undergraduate/courses-registration/exams-assessment/midterms-and-class-tests/adjustments-missed-midterms-and-class-tests

[charter]: https://www.mcgill.ca/secretariat/files/secretariat/charter_of_student_rights_last_approved_october_262017.pdf

[code]: https://www.mcgill.ca/secretariat/files/secretariat/code_of_student_conduct_and_disciplinary_procedures.pdf

[guide]: http://www.mcgill.ca/students/srr/honest/

[evaluations]: http://www.mcgill.ca/mercury/

[OSD]: https://www.mcgill.ca/access-achieve/

